export const products=[
    {
        id:'1',
        quantity:1,
        category:'jeans',
        cloth:'jeans',
        price:'1200',
        color:'blue',
        type:'bottomwear',
        url:'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTAM3iLrPXoaC76AedncBHFGWrIZiuCrlFUxJSlDe2wujaO_JzfvYnWXblPC6z7GhfAzfvdz00YgEjaiJ4xI-_tVUscibuQCUU4D94tbOW4z0e6ox-d0SLZ&usqp=CAc'
    },
    {
        id:'2',
        quantity:1,
        category:'trouser',
        cloth:'Cotton',
        price:'1000',
        color:'white',
        type:'bottomwear',
        url:'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQiwqu0cyalGlCkTeLYdSeHlOy92DwQlHHnyXQcFVQmlEwhfu3LACpUcLdIGmmaHUwp-wX6otk280WkkJJMgwReB-skFAHjlx6m5xJVBmoZ4Db6bn_NgF4jK3M'
    },
    {
        id:'3',
        quantity:1,
        category:'jogger',
        cloth:'Cotton',
        price:'900',
        color:'navyBlue',
        type:'bottomwear',
        url:'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTnOGU3jQEObQEqlrXOLqXXoZJk49Gdzc9tQp4G-KIWt9Y-oTbX4jWGJL16d9QfGobraKFxfhI47IevZqHj-5-TIsNX9cEAUoVYV6UiUDGREAJKNq4fz8VcNg'
    },
    {
        id:'4',
        quantity:1,
        category:'jeans',
        cloth:'jeans',
        price:'1500',
        color:'grey',
        type:'bottomwear',
        url:'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS4eVxnnGgdRhRVfCIi1fFDFTxbDV3WrEe1h4nz-UpO2t6xdJ8h7eJ4jGn9qkWd4lD_WtNwl_-yduo4loN_GH3I7sb6UU8kZnu_K7x19ZI'
    },
    {
        id:'5',
        quantity:1,
        category:'trouser',
        cloth:'cottton',
        price:'1800',
        color:'navyBlue',
        type:'bottomwear',
        url:'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSTxWib9yTSjT7h3or5lquRus0li1k6LxL3Caih-38RgKdywIgwzy-RQMTup7eladfFd9gyH-QjRt8g0nNWP6YJ0ri2T2TSDlXhFMs-r6rCz-AOS0R2LqGB'
    },
    {
        id:'6',
        quantity:1,
        category:'T-Shirt',
        cloth:'Cotton',
        price:'1600',
        color:'red',
        type:'topwear',
        url:'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQxjSM57gjmwj7bwtmNP0JNfM7NWs6p8sAenlw2c4GRw1aH1bLt6H_GSiHWeftgCWx_pYtCEJjPGJSn78fXnZBQvTwUAXRtWrv2etasgE-ZTxHaiJZJLJewBxk5TpKts37Dcc_dq0w&usqp=CAc'
    },
    {
        id:'7',
        quantity:1,
        category:'T-Shirt',
        cloth:'Cotton',
        price:'600',
        color:'orange',
        type:'topwear',
        url:'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQcU2QO0SLd9yjdEriic_A9Sz02MCVPYEwJc4CLefcymzm-5oAML8nV3vAD0ZZ1yJF7EVvsnMTHXiF17zwKrjZ3-jM0Jn9CxxFriw7dG60_0FNzFQ90vBRWApWt81RJgEaMmZ-aCXlI0VE&usqp=CAc'
    },
    {
        id:'8',
        quantity:1,
        category:'Shirt',
        cloth:'Cotton',
        price:'1000',
        color:'white',
        type:'topwear',
       url:'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ5tOxIpOe0MJd2F5CvAuFsqr4TJPHbcZM9DbEjrao0t9xOdsyVEwmCvvkFBM_e0850gTQ-eYbuaCyyjSQhJa_RnNIHw88ousKUPMe5TpwzLqfiIaxXXCf4&usqp=CAc'
    },
    {
        id:'9',
        quantity:1,
        category:'T-Shirt',
        cloth:'Cotton',
        price:'800',
        color:'blue',
        type:'topwear',
        url:'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRKa0nlXUVZUroqBPo4gJieiPMjvweUdhDHo8mgUiinOUKJZXUwQO3f1jwVrXwJegUE2B-GvL3KOMNrPJxjOdrgSGaStkyZrN1tu7P5WegAzM83sB4au83oXxKnglqDVj6zaSiFUZQAQg&usqp=CAc'
    },
    {
        id:'10',
        quantity:1,
        category:'T-Shirt',
        cloth:'Cotton',
        price:'500',
        color:'yellow',
        type:'topwear',
        url:'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQcU2QO0SLd9yjdEriic_A9Sz02MCVPYEwJc4CLefcymzm-5oAML8nV3vAD0ZZ1yJF7EVvsnMTHXiF17zwKrjZ3-jM0Jn9CxxFriw7dG60_0FNzFQ90vBRWApWt81RJgEaMmZ-aCXlI0VE&usqp=CAc'
    },
    {
        id:'11',
        quantity:1,
        category:'jacket',
        cloth:'leather',
        price:'1500',
        color:'black',
        type:'topwear',
        url:'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQr85rEaECv0_alhE54Qmb1GnZdVRYZH_NFtC0X0aeFm2Z5XmJCj6u8GQOLisHzMOgQgB6R3fjqTBKB3kkZHydX5wIUrMur8dQ88--XR90'
    },
    
]